# Generated by Django 2.0.3 on 2018-03-20 06:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auditor_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('feedback_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FeedbackForm')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='feedbackacademics',
            name='student',
        ),
        migrations.RemoveField(
            model_name='feedbackfacultytheory',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='feedbackfacultytheory',
            name='student',
        ),
        migrations.RemoveField(
            model_name='feedbackinfrastructure',
            name='student',
        ),
        migrations.RenameModel(
            old_name='Teaches',
            new_name='TeacherSubject',
        ),
        migrations.DeleteModel(
            name='FeedbackAcademics',
        ),
        migrations.DeleteModel(
            name='FeedbackFacultyTheory',
        ),
        migrations.DeleteModel(
            name='FeedbackInfrastructure',
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuestionType'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
        migrations.AddField(
            model_name='feedbackresponse',
            name='teacher_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TeacherSubject'),
        ),
    ]
