# Generated by Django 2.0.3 on 2018-03-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180320_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextualResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('feedback_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FeedbackForm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student')),
                ('teacher_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.TeacherSubject')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuestionType')),
            ],
        ),
    ]
